a = input("Digite algo: ")
print('o tipo primitivo desse valor é, ', type(a))
print('só tem espacos ?, ', a.isspace())
print('é um numero ?, ', a.isnumeric())
print('é alfabetico ?, ', a.isalpha())
print('é maiscula ?, ', a.isupper())
print('é minuscula ?, ', a.islower())
print('é capitalizada ?, ', a.istitle())